name: Pytest Coverage

on:
  pull_request:
    branches:
    - main # Runs on PRs targeting the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_pytest_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event_name == 'pull_request' && github.head_ref || 'main' }}
        fetch-depth: 0
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install requirements and add python path
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov coverage-badge
        
    - name: Create reports directory
      run: |
        mkdir -p build/reports
    
    - name: Run pytest with coverage
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest --cov --cov-report=html --cov-report=xml --cov-report=term
    
    - name: Generate coverage badge
      run: |
        coverage-badge -o build/reports/coverage.svg -f
        
    - name: Check if badge changed
      id: badge-check
      run: |
        if git diff --quiet HEAD -- build/reports/coverage.svg 2>/dev/null || [ ! -f build/reports/coverage.svg ]; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push coverage badge
      if: steps.badge-check.outputs.changed == 'true' && github.event_name == 'pull_request'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add build/reports/coverage.svg
        git commit -m "Update coverage badge [skip ci]"
        git push origin ${{ github.head_ref }}
        
    - name: Upload coverage badge as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: build/reports/coverage.svg
        retention-days: 30
        
    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html-report
        path: build/reports/coverage_html/
        retention-days: 30