name: Verify Installation

on:
  pull_request:
    branches:
    - main # Runs on PRs targeting the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install requirements and add python path
      run: |
        python -m pip install --upgrade pip
        pip install .
    # Runs simple verification script
    - name: Verify installation with simple example script
      run: python unittests/verify_installation.py
