name: Verify Executables

on:
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      scripts: ${{ steps.changed_files_py.outputs.all_changed_files }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Python files
        id: changed_files_py
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: |
            executables/**.py
          json: true
          
      - name: Save changed files JSON to artifact
        run: |
          echo '${{ steps.changed_files_py.outputs.all_changed_files }}' > changed_files.json
          
      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-python-files
          path: changed_files.json
          retention-days: 30

  run-scripts:
    needs: setup
    if: needs.setup.outputs.scripts != '[]' && needs.setup.outputs.scripts != ''
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        script: ${{ fromJSON(needs.setup.outputs.scripts) }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install requirements and add python path
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script -> ${{ matrix.script }}
      run: python ${{ matrix.script }}